language: node_js
node_js:
  - "8"
  - "node"
install:
  - yarn
branches:
  except:
    - gh-pages
stages:
  - lint
  - test
  - build
jobs:
  include:
    - stage: lint
      script:
        # Run linter
        - yarn lint
    - stage: test
      script:
        # Run tests
        - yarn test
    - stage: build
      script:
        # Build all
        - yarn build:docs
        - yarn build:system
        - yarn build:app
